definitions:
  Example:
    description: Represents a example
    properties:
      exampleID:
        type: integer
      exampleString:
        type: string
      dateAdded:
        type: string
        format: date
      dateTimeAdded:
        type: string
        format: date-time
      lastUpdatedDateTime:
        type: string
        format: date-time
  RespondError:
    description: Model used for responding with an error
    properties:
      message:
        type: string
    example:
      message: This is a bad request
parameters:
  Authorization:
    name: Authorization
    in: header
    description: JWT token in `Bearer token` format, where `token` is your JWT token.
    required: true
    type: string
  ExampleIDParam:
    name: exampleID
    in: path
    description: ID of the example on which to perform the operation
    type: integer
  PostEmployeeRequestPayload:
    name: body
    in: body
    description: Body of the POST request
    required: true
    schema: 
      $ref: '#/definitions/Example'
  PatchExampleRequestPayload:
    name: body
    in: body
    description: Body of the PATCH request
    required: true
    schema:
      $ref: '#/definitions/Example'